---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: arthur-serverless-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arthur-serverless-redis
  template:
    metadata:
      labels:
        app: arthur-serverless-redis
    spec:
      containers:
      - name: arthur-serverless-redis
        image: arthursl12/arthur-serverless-redis:0.3
        # For debugging only
        command: [ "sh", "-c"]
        # loop forever, outputting "yo" every 5 seconds
        args: ["while true; do echo 'yo' && sleep 5; done;"]

        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 300Mi
        volumeMounts:
        - name: pyfile
          mountPath: "/opt/usermodule.py"
          subPath: "pyfile"
        env:
        - name: REDIS_HOST
          value: "192.168.121.189"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_INPUT_KEY
          value: "metrics"
        - name: REDIS_OUTPUT_KEY
          valueFrom:
            configMapKeyRef:
              name: outputkey
              key: REDIS_OUTPUT_KEY
      volumes:
      - name: pyfile
        configMap:
          name: pyfile

