---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: arthur-dashboard-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: arthur-dashboard
  template:
    metadata:
      labels:
        app: arthur-dashboard
    spec:
      containers:
      - name: arthur-dashboard
        image: arthursl12/arthur-dashboard:1.1
        ports:
        - containerPort: 5102
        - containerPort: 5102